name = "factos_pog"
version = "2.0.0"
description = "PostgreSQL backend for Factos context-first Event Sourcing using pog."
licences = ["MIT"]
links = [
  { title = "Factos", href = "https://factos.hexdocs.pm" },
  { title = "Simply Event Sourcing", href = "https://ricofritzsche.me/simply-event-sourcing/" },
]
[repository]
type = "github"
user = "renatillas"
repo = "factos_pog"

[[documentation.pages]]
title = "How factos_pog Works"
path = "how-it-works.html"
source = "./docs/how-it-works.md"

[dependencies]
factos = { git = "https://github.com/renatillas/factos", ref = "main" } 
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
pog = ">= 4.1.0 and < 5.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
testcontainer = ">= 1.0.2 and < 2.0.0"
testcontainer_formulas = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.5.0 and < 3.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
